INSERT INTO scienza.permiso (id, fecha_delete, fecha_insert, fecha_update, version, nombre, descripcion) VALUES (1, null, '2018-10-16 11:11:27', null, 0, 'DSHADM', 'Dashboard Administrador');
INSERT INTO scienza.permiso (id, fecha_delete, fecha_insert, fecha_update, version, nombre, descripcion) VALUES (2, null, '2018-10-16 11:11:27', null, 0, 'ALTPEN', 'Gestión de Altas Pendientes');
INSERT INTO scienza.permiso (id, fecha_delete, fecha_insert, fecha_update, version, nombre, descripcion) VALUES (3, null, '2018-10-16 11:11:27', null, 0, 'PERPEN', 'Gestión de Perfiles Pendientes');
INSERT INTO scienza.permiso (id, fecha_delete, fecha_insert, fecha_update, version, nombre, descripcion) VALUES (4, null, '2018-10-16 11:11:27', null, 0, 'CONPEN', 'Gestión de Consultas Pendientes');
INSERT INTO scienza.permiso (id, fecha_delete, fecha_insert, fecha_update, version, nombre, descripcion) VALUES (5, null, '2018-10-16 11:11:27', null, 0, 'ENVMEN', 'Envío de mensajes a un afiliado');
INSERT INTO scienza.permiso (id, fecha_delete, fecha_insert, fecha_update, version, nombre, descripcion) VALUES (6, null, '2018-10-16 11:11:27', null, 0, 'TEMPLA', 'Gestión de Templates de Mensaje');
INSERT INTO scienza.permiso (id, fecha_delete, fecha_insert, fecha_update, version, nombre, descripcion) VALUES (7, null, '2018-10-16 11:11:27', null, 0, 'GOOMAP', 'Información de Google Maps');
INSERT INTO scienza.permiso (id, fecha_delete, fecha_insert, fecha_update, version, nombre, descripcion) VALUES (8, null, '2018-10-16 11:11:27', null, 0, 'ONESIG', 'Actualización del playerId');
INSERT INTO scienza.permiso (id, fecha_delete, fecha_insert, fecha_update, version, nombre, descripcion) VALUES (9, null, '2018-10-16 11:11:27', null, 0, 'ENTITY', 'Entidades del sistema');
INSERT INTO scienza.permiso (id, fecha_delete, fecha_insert, fecha_update, version, nombre, descripcion) VALUES (10, null, '2018-10-16 11:11:27', null, 0, 'DSHAFI', 'Dashboard Afiliado');
INSERT INTO scienza.permiso (id, fecha_delete, fecha_insert, fecha_update, version, nombre, descripcion) VALUES (11, null, '2018-10-16 11:11:27', null, 0, 'PERAFI', 'Perfil Afiliado');
INSERT INTO scienza.permiso (id, fecha_delete, fecha_insert, fecha_update, version, nombre, descripcion) VALUES (12, null, '2018-10-16 11:11:27', null, 0, 'ADDAFI', 'Vincular Afiliado');
INSERT INTO scienza.permiso (id, fecha_delete, fecha_insert, fecha_update, version, nombre, descripcion) VALUES (13, null, '2018-10-16 11:11:27', null, 0, 'DELAFI', 'Desvincular Afiliado');
INSERT INTO scienza.permiso (id, fecha_delete, fecha_insert, fecha_update, version, nombre, descripcion) VALUES (14, null, '2018-10-16 11:11:27', null, 0, 'PEDAFI', 'Pedidos del Afiliado');
INSERT INTO scienza.permiso (id, fecha_delete, fecha_insert, fecha_update, version, nombre, descripcion) VALUES (15, null, '2018-10-16 11:11:27', null, 0, 'PEDCOR', 'Coordinación de Pedidos');
INSERT INTO scienza.permiso (id, fecha_delete, fecha_insert, fecha_update, version, nombre, descripcion) VALUES (16, null, '2018-10-16 11:11:27', null, 0, 'CONAFI', 'Consultas del Afiliado');
INSERT INTO scienza.permiso (id, fecha_delete, fecha_insert, fecha_update, version, nombre, descripcion) VALUES (17, null, '2018-10-16 11:11:27', null, 0, 'NOTAFI', 'Notificaciones del Afiliado');
INSERT INTO scienza.permiso (id, fecha_delete, fecha_insert, fecha_update, version, nombre, descripcion) VALUES (18, null, '2018-10-16 11:11:27', null, 0, 'DOCAFI', 'Documentación del Afiliado');
INSERT INTO scienza.permiso (id, fecha_delete, fecha_insert, fecha_update, version, nombre, descripcion) VALUES (19, null, '2018-10-16 11:11:27', null, 0, 'VERTRA', 'Verificación de Trazas');
INSERT INTO scienza.permiso (id, fecha_delete, fecha_insert, fecha_update, version, nombre, descripcion) VALUES (20, null, '2018-10-16 11:11:27', null, 0, 'PREGFR', 'Preguntas Frecuentes');
INSERT INTO scienza.permiso (id, fecha_delete, fecha_insert, fecha_update, version, nombre, descripcion) VALUES (21, null, '2018-10-16 11:11:27', null, 0, 'TERCON', 'Términos y Condiciones');
INSERT INTO scienza.permiso (id, fecha_delete, fecha_insert, fecha_update, version, nombre, descripcion) VALUES (22, null, '2018-10-16 11:12:28', null, 0, 'REPADM', 'Reportes Administrativos');
INSERT INTO scienza.permiso (id, fecha_delete, fecha_insert, fecha_update, version, nombre, descripcion) VALUES (23, null, '2019-03-11 12:51:14', null, 0, 'HISMEN', 'Historial de mensajes enviados');
INSERT INTO scienza.permiso (id, fecha_delete, fecha_insert, fecha_update, version, nombre, descripcion) VALUES (24, null, '2019-04-03 14:15:40', null, 0, 'BUSDIS', 'Busqueda de dispone');
INSERT INTO scienza.permiso (id, fecha_delete, fecha_insert, fecha_update, version, nombre, descripcion) VALUES (25, null, '2019-07-29 15:39:15', null, 0, 'AFISG', 'Afiliados de Seguro Médico');
INSERT INTO scienza.permiso (id, fecha_delete, fecha_insert, fecha_update, version, nombre, descripcion) VALUES (26, null, '2019-07-30 14:29:17', null, 0, 'REGPM', 'Registro de Personal Médico');
INSERT INTO scienza.permiso (id, fecha_delete, fecha_insert, fecha_update, version, nombre, descripcion) VALUES (27, null, '2019-08-01 12:16:53', null, 0, 'DSHPM', 'Dashboard Personal Medico');
INSERT INTO scienza.permiso (id, fecha_delete, fecha_insert, fecha_update, version, nombre, descripcion) VALUES (29, null, '2019-08-07 10:43:31', null, 0, 'ABMPM', 'ABM de Personal Médico');
